In [1]:
import numpy as np
from sklearn import linear_model

In [2]:
regr = linear_model.LinearRegression()

In [3]:
xi = np.array([64, 256, 512])
y = np.array([32500000, 36000000, 42000000])


In [13]:
xi.reshape(-1, 1)

array([[ 64],
       [256],
       [512]])

In [11]:
regr.fit(xi.reshape(-1, 1), y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
print(regr.coef_, regr.intercept_)


[21326.01351351] 30918918.918918923


In [6]:
regr.intercept_ + regr.coef_

array([52756756.75675676])

In [7]:
print(regr.predict(512))

[41837837.83783785]


In [15]:
regr.

TypeError: score() missing 2 required positional arguments: 'X' and 'y'

In [12]:
regr.coef_ 

array([21326.01351351])